name: TEST ACTIONS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make migrate
      run: |
        cd places_remember
        ls -a
        python manage.py migrate
    - name: Run tests
      run: |
        cd places_remember
        ls -a
        python manage.py test
